namespace OE.Tudasbazis.Application.Services.EmbeddingService
{
	public interface IEmbeddingService
	{
		/// <summary>
		///		Generates embeddings for the given text.
		/// </summary>
		/// <param name="text">Text to embed</param>
		/// <returns>Dense vector generated by the given text.</returns>
		float[] GetEmbeddings(string text);
	}
}
