namespace OE.Tudasbazis.Application.Services
{
	public interface IEmbeddingService
	{
		/// <summary>
		///		Generates embeddings for the given text.
		/// </summary>
		/// <param name="text">Text to embed</param>
		/// <returns>Dense vector generated by the given text.</returns>
		Task<float[]> GetEmbeddingsAsync(string text);
	}
}
