name: Build and deploy ASP.Net Core app to Azure Web App - oe-tudasbizs

on:
    push:
        branches:
            - develop
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: oe-tudasbazis
    AZURE_WEBAPP_PACKAGE_PATH: ./publish
    SOLUTION_LOCATION: ./src/OE.Tudasbazis/

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Run .NET Restore
        run: dotnet restore ${{env.SOLUTION_LOCATION}}

      - name: Run .NET Build
        run: dotnet build --configuration Release ${{env.SOLUTION_LOCATION}} --no-restore

      - name: Run .NET Publish
        run: dotnet publish ${{env.SOLUTION_LOCATION}} --configuration Release --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
            slot-name: 'Production'
            app-name: ${{env.AZURE_WEBAPP_NAME}}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}