# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - oe-tudasbazis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./src/OE.Tudasbazis/OE.Tudasbazis.Web/OE.Tudasbazis.Web/ --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/OE.Tudasbazis/OE.Tudasbazis.Web/OE.Tudasbazis.Web/ -c Release -o ${{env.DOTNET_ROOT}}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/publish

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      - name: Clean up existing files in Azure Web App
        run: az webapp deploy delete --name oe-tudasbazis --resource-group abelm-oe-tudasbazis --slot Production

  deploy:
    runs-on: windows-latest
    needs: [build, cleanup]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './appsettings.json'
        env:
         ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
         Jwt.Key: ${{ secrets.JWT_SECRET }}
         Jwt.Issuer: ${{ secrets.APP_URL }}
         Jwt.Audience: ${{ secrets.APP_URL }}
         ElasticSearch.Url: ${{ secrets.ELASTICSEARCH_URL }}
         ElasticSearch.IndexName: ${{ secrets.ELASTICSEARCH_INDEXNAME }}
         ElasticSearch.ApiKey: ${{ secrets.ELASTICSEARCH_APIKEY }}
         OpenAi.DeploymentId: ${{ secrets.OPENAI_DEPLOYMENTID }}
         OpenAi.ApiKey: ${{ secrets.OPENAI_APIKEY }}
         OpenAi.Endpoint: ${{ secrets.OPENAI_ENDPOINT }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'oe-tudasbazis'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
